Lower permissions on openstack-dashboard logrotate
Error: Ignoring openstack-dashboard because of bad file mode.

/etc/logrotate.d/openstack-dashboard has chmod 664 which logrotate
does not like and thus ignores reading that config file.

Reducing it to 644 makes it run.

- logrotate-3.8.6-12.el7.x86_64
- openstack-dashboard-10.0.3-1.el7.noarch

Change-Id: Ib970f7d69521724c92669b5fab2045651efed0aa